### ISSUE TITLE
Undefined locations for result cards

### ISSUE THREAD

**Issue by apriljgranzow** [Ideal-Media-Solutions-LLC/buskr#54]
![i_view64_AAzEZIxap6](https://user-images.githubusercontent.com/4971311/146288504-8ec8c3c2-754c-4eaa-b700-67fd2def4a30.png)

**Comment by apriljgranzow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Result cards displaying undefined for location](https://trello.com/c/9vO0Nw0m/118-result-cards-displaying-undefined-for-location)

**Comment by jnbooth** [comment]
Should be resolved by #61.
