### ISSUE TITLE
Links on result cards not going to the right place

### ISSUE THREAD

**Issue by apriljgranzow** [Ideal-Media-Solutions-LLC/buskr#55]
When I click on an event title from search results, it takes me to the url, for example, https://development.buskr.life/event/1979 . This renders as a 404 error.
When I click on the busker name, it displays a 500 error, at this URL. https://development.buskr.life/profile/82558207-35b0-46b6-ac0c-aa52d98f4740
Next.js prints an error to the console as follows: 
```
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

**Comment by jnbooth** [comment]
This is happening because the events page is pulling its list of events from buskr.life, but the page for a single event retrieves from your local database. The local-databases PR that was just merged should fix that.
